[package]
name = "unit-conversion"
version = "0.1.0"
authors = ["eindiran <eindiran@uchicago.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
measurements = "0.10.3"
